"""initial_schema

Revision ID: d65666c751dc
Revises:
Create Date: 2026-05-31 22:30:42.687301

"""

from __future__ import annotations

import warnings
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

with warnings.catch_warnings():
    warnings.simplefilter("ignore", UserWarning)
    from app.core.config import settings

_schema = settings.database.schema

# revision identifiers, used by Alembic.
revision: str = "d65666c751dc"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_store",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("is_new_user", sa.Boolean(), nullable=False),
        sa.Column("total_sessions", sa.Integer(), nullable=False),
        sa.Column("total_pageviews", sa.Integer(), nullable=False),
        sa.Column("active_days", sa.Integer(), nullable=False),
        sa.Column(
            "avg_session_duration", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column(
            "avg_pages_per_session", sa.Numeric(precision=8, scale=4), nullable=False
        ),
        sa.Column("bounce_rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("mobile_ratio", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("desktop_ratio", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "pageviews_per_session", sa.Numeric(precision=8, scale=4), nullable=False
        ),
        sa.Column("days_since_last_visit", sa.Integer(), nullable=False),
        sa.Column("account_age_days", sa.Integer(), nullable=False),
        sa.Column("ratio_sports", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "ratio_entertainment", sa.Numeric(precision=5, scale=4), nullable=False
        ),
        sa.Column("ratio_celebrity", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("ratio_shopping", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("ratio_opinion", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("ratio_world_news", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("ratio_business", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("ratio_lifestyle", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("has_subscription", sa.Boolean(), nullable=False),
        sa.Column(
            "subscription_amount", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("total_billing_cycles", sa.Integer(), nullable=False),
        sa.Column("days_until_renewal", sa.Integer(), nullable=False),
        sa.Column("newsletter_count", sa.SmallInteger(), nullable=False),
        sa.Column("open_rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "click_through_rate", sa.Numeric(precision=5, scale=4), nullable=False
        ),
        sa.Column("email_engagement_score", sa.SmallInteger(), nullable=False),
        sa.Column("nl_sports_alerts", sa.Boolean(), nullable=False),
        sa.Column("nl_morning_report", sa.Boolean(), nullable=False),
        sa.Column("nl_page_six_daily", sa.Boolean(), nullable=False),
        sa.Column("nl_celebrity_news", sa.Boolean(), nullable=False),
        sa.Column("nl_evening_update", sa.Boolean(), nullable=False),
        sa.Column("nl_post_opinion", sa.Boolean(), nullable=False),
        sa.Column("nl_breaking_news", sa.Boolean(), nullable=False),
        sa.Column("nl_real_estate", sa.Boolean(), nullable=False),
        sa.Column("nl_tech_news", sa.Boolean(), nullable=False),
        sa.Column("nl_lifestyle_weekly", sa.Boolean(), nullable=False),
        sa.Column("total_comments", sa.Integer(), nullable=False),
        sa.Column("total_likes_given", sa.Integer(), nullable=False),
        sa.Column("total_shares", sa.Integer(), nullable=False),
        sa.Column("social_engagement_score", sa.Integer(), nullable=False),
        sa.Column("total_affiliate_clicks", sa.Integer(), nullable=False),
        sa.Column("total_transactions", sa.Integer(), nullable=False),
        sa.Column(
            "total_revenue_generated", sa.Numeric(precision=12, scale=2), nullable=False
        ),
        sa.Column("conversion_rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "avg_transaction_value", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("unique_advertisers_clicked", sa.Integer(), nullable=False),
        sa.Column("age_score", sa.SmallInteger(), nullable=False),
        sa.Column("income_score", sa.SmallInteger(), nullable=False),
        sa.Column("has_children", sa.Boolean(), nullable=False),
        sa.Column("persona_label", sa.String(length=50), nullable=True),
        sa.Column("cluster_id", sa.SmallInteger(), nullable=True),
        sa.Column("algorithm_used", sa.String(length=50), nullable=True),
        sa.Column("cluster_score", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column(
            "subscription_propensity_score",
            sa.Numeric(precision=6, scale=4),
            nullable=True,
        ),
        sa.Column(
            "churn_propensity_score", sa.Numeric(precision=6, scale=4), nullable=True
        ),
        sa.Column(
            "commerce_propensity_score", sa.Numeric(precision=6, scale=4), nullable=True
        ),
        sa.Column("soft_persona_scores", sa.Text(), nullable=True),
        sa.Column("cluster_top_features", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
        schema=_schema,
    )
    op.create_table(
        "zephr_users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("hashed_email", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("account_age_days", sa.Integer(), nullable=False),
        sa.Column("is_registered", sa.Boolean(), nullable=False),
        sa.Column("registration_date", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
        schema=_schema,
    )
    op.create_table(
        "braintree_subscriptions",
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("braintree_customer_id", sa.String(length=50), nullable=False),
        sa.Column("plan_id", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("billing_cycle_count", sa.Integer(), nullable=False),
        sa.Column("next_billing_date", sa.Date(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("canceled_at", sa.DateTime(), nullable=True),
        sa.Column("payment_method", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["public.zephr_users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("subscription_id"),
        sa.UniqueConstraint("braintree_customer_id"),
        schema=_schema,
    )
    op.create_table(
        "ga4_events",
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("user_pseudo_id", sa.String(length=64), nullable=False),
        sa.Column("event_name", sa.String(length=100), nullable=False),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("event_timestamp", sa.DateTime(), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column("device_category", sa.String(length=50), nullable=True),
        sa.Column("page_category", sa.String(length=50), nullable=True),
        sa.Column("page_path", sa.Text(), nullable=True),
        sa.Column("engagement_time_msec", sa.Integer(), nullable=False),
        sa.Column("is_bounce", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["public.zephr_users.user_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("event_id"),
        schema=_schema,
    )
    op.create_table(
        "ga4_identity_bridge",
        sa.Column("bridge_id", sa.UUID(), nullable=False),
        sa.Column("user_pseudo_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["public.zephr_users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("bridge_id"),
        sa.UniqueConstraint("user_pseudo_id"),
        schema=_schema,
    )
    op.create_table(
        "openweb_engagement",
        sa.Column("engagement_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=20), nullable=False),
        sa.Column("content_id", sa.String(length=100), nullable=True),
        sa.Column("content_category", sa.String(length=50), nullable=True),
        sa.Column("engaged_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["public.zephr_users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("engagement_id"),
        schema=_schema,
    )
    op.create_table(
        "pushly_subscribers",
        sa.Column("subscriber_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("platform", sa.String(length=20), nullable=False),
        sa.Column("push_opted_in", sa.Boolean(), nullable=False),
        sa.Column("push_is_active", sa.Boolean(), nullable=False),
        sa.Column("opted_in_at", sa.DateTime(), nullable=False),
        sa.Column("opted_out_at", sa.DateTime(), nullable=True),
        sa.Column("last_push_sent_at", sa.DateTime(), nullable=True),
        sa.Column("push_open_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["public.zephr_users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("subscriber_id"),
        sa.UniqueConstraint("external_id"),
        schema=_schema,
    )
    op.create_table(
        "sailthru_newsletter",
        sa.Column("record_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("newsletter_count", sa.SmallInteger(), nullable=False),
        sa.Column("open_rate", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column(
            "click_through_rate", sa.Numeric(precision=5, scale=4), nullable=False
        ),
        sa.Column("email_engagement_score", sa.SmallInteger(), nullable=False),
        sa.Column("engagement_tier", sa.String(length=10), nullable=True),
        sa.Column("subscribed_newsletters", sa.Text(), nullable=True),
        sa.Column("nl_sports_alerts", sa.Boolean(), nullable=False),
        sa.Column("nl_morning_report", sa.Boolean(), nullable=False),
        sa.Column("nl_page_six_daily", sa.Boolean(), nullable=False),
        sa.Column("nl_celebrity_news", sa.Boolean(), nullable=False),
        sa.Column("nl_evening_update", sa.Boolean(), nullable=False),
        sa.Column("nl_post_opinion", sa.Boolean(), nullable=False),
        sa.Column("nl_breaking_news", sa.Boolean(), nullable=False),
        sa.Column("nl_real_estate", sa.Boolean(), nullable=False),
        sa.Column("nl_tech_news", sa.Boolean(), nullable=False),
        sa.Column("nl_lifestyle_weekly", sa.Boolean(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["public.zephr_users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("record_id"),
        schema=_schema,
    )
    op.create_table(
        "trackonomics_clicks",
        sa.Column("click_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("advertiser_id", sa.String(length=100), nullable=False),
        sa.Column("product_category", sa.String(length=30), nullable=True),
        sa.Column("click_timestamp", sa.DateTime(), nullable=False),
        sa.Column("converted", sa.Boolean(), nullable=False),
        sa.Column("transaction_id", sa.String(length=100), nullable=True),
        sa.Column(
            "transaction_amount", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["public.zephr_users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("click_id"),
        schema=_schema,
    )
    op.create_table(
        "transunion_demographics",
        sa.Column("demo_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("hashed_email", sa.String(length=64), nullable=False),
        sa.Column("match_confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("excluded", sa.Boolean(), nullable=False),
        sa.Column("age_range", sa.String(length=20), nullable=True),
        sa.Column("gender", sa.String(length=10), nullable=True),
        sa.Column("income_range", sa.String(length=20), nullable=True),
        sa.Column("has_children", sa.Boolean(), nullable=True),
        sa.Column("home_ownership", sa.String(length=10), nullable=True),
        sa.Column("education", sa.String(length=20), nullable=True),
        sa.Column("address_state", sa.String(length=2), nullable=True),
        sa.Column("address_zip", sa.String(length=10), nullable=True),
        sa.Column("match_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["public.zephr_users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("demo_id"),
        sa.UniqueConstraint("user_id"),
        schema=_schema,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transunion_demographics", schema=_schema)
    op.drop_table("trackonomics_clicks", schema=_schema)
    op.drop_table("sailthru_newsletter", schema=_schema)
    op.drop_table("pushly_subscribers", schema=_schema)
    op.drop_table("openweb_engagement", schema=_schema)
    op.drop_table("ga4_identity_bridge", schema=_schema)
    op.drop_table("ga4_events", schema=_schema)
    op.drop_table("braintree_subscriptions", schema=_schema)
    op.drop_table("zephr_users", schema=_schema)
    op.drop_table("feature_store", schema=_schema)
    # ### end Alembic commands ###
